"""Ingestion Bridge v2 contracts and service adapters."""

from .contracts import (
    AgentRunRecord,
    ArtifactHandle,
    AsyncRunHandle,
    BackfillResult,
    CandidateDossier,
    ClaimCurationItem,
    ClaimCurationRequest,
    ClaimCurationResult,
    ClaimExtractionResult,
    ClaimSearchResult,
    ClaimSearchResults,
    CommitHypothesisRequest,
    DocumentChunk,
    EvidenceFitAssessment,
    EvidenceGapResolverRequest,
    EvidenceGapResolverResult,
    FullTextTriageRequest,
    FullTextTriageResult,
    FullTextOpsAction,
    FullTextOpsRequest,
    FullTextOpsResult,
    HypothesisPromotionCandidate,
    HypothesisPromotionReportRequest,
    HypothesisPromotionReportResult,
    HypothesisDraft,
    HypothesisProposalRequest,
    IngestionResult,
    ResearchBriefEvaluationRecord,
    ResearchBriefEvaluationRequest,
    ResearchBriefEvaluationResult,
    ResearchFollowupLeadResult,
    ResearchFollowupLoopRequest,
    ResearchFollowupLoopResult,
    ResearchFollowupRefinementRequest,
    ResearchFollowupRefinementResult,
    ResearchFollowupResolverRequest,
    ResearchFollowupResolverResult,
    ResearchSource,
    RetrievalSmokeRequest,
    RetrievalSmokeResult,
    SearchClaimsRequest,
    SourceQuery,
    SourceRecommendation,
    SourceScoutRequest,
    SourceScoutResult,
    TherapyCommitteeReport,
    TherapyCommitteeRequest,
    TherapyCommitteeResult,
    TherapyCommitteeValidationQueueRequest,
    TherapyCommitteeValidationQueueResult,
    TherapyIdea,
    TherapyIdeaLibraryRequest,
    TherapyIdeaLibraryResult,
    TherapyIdeaRecord,
    ValidationAssayContext,
    ValidationAgentResult,
    ValidationGapSourceIngestRequest,
    ValidationGapSourceIngestResult,
    ValidationGapSourcePackRequest,
    ValidationGapSourcePackResult,
    ValidationGapSourceQuery,
    ValidationPacket,
    ValidationPacketRequest,
    ValidationPacketResult,
    ValidationRequest,
    ValidationRequestQueueItem,
    ValidationRequestQueueRequest,
    ValidationRequestQueueResult,
    ValidationToolCapability,
    ValidationToolCatalogRequest,
    ValidationToolCatalogResult,
    ValidationToolMatchRequest,
    ValidationToolMatchResult,
    XLinkedArticleFollowupRequest,
    XLinkedArticleFollowupResult,
    XTopicLinkedSource,
    XTopicReviewAction,
    XTopicReviewRequest,
    XTopicReviewResult,
)
from .claim_curator import ClaimCuratorAgent, curate_claims_for_repository
from .embeddings import (
    EmbeddingIndexResult,
    EmbeddingMaintenanceResult,
    LocalDeterministicEmbeddingProvider,
    OpenRouterEmbeddingProvider,
    build_chunk_embedding_text,
    build_embedding_provider,
    index_embeddings_for_repository,
    maintain_embedding_index,
)
from .harvesters_v2 import (
    CrossrefHarvesterV2,
    EuropePMCHarvesterV2,
    OpenAlexHarvesterV2,
    PubMedHarvesterV2,
    get_harvester,
)
from .local_ingest import LocalIngestionPipeline
from .claim_extractor import LocalRuleClaimExtractor, extract_claims_for_repository
from .full_text_triage import FullTextTriageAgent, triage_full_text_issue
from .full_text_ops import FullTextOpsAgent
from .research_followup_resolver import resolve_research_followup_leads
from .query_policy import build_scholarly_source_queries, comparative_required_query
from .service import HSAResearchService, get_service
from .local_store import SQLiteResearchRepository
from .postgres_store import PostgresResearchRepository
from .source_scout import SourceScoutAgent, scout_sources_for_repository
from .storage import build_research_repository, build_sql_repository
from .therapy_committee import run_therapy_committee
from .validation_tool_catalog import build_validation_tool_catalog_report, match_validation_tools
from .x_topic_review import XTopicReviewAgent
from .x_linked_article_followup import run_x_linked_article_followup

__all__ = [
    "ArtifactHandle",
    "AgentRunRecord",
    "AsyncRunHandle",
    "BackfillResult",
    "CandidateDossier",
    "ClaimCurationItem",
    "ClaimCurationRequest",
    "ClaimCurationResult",
    "ClaimExtractionResult",
    "ClaimSearchResult",
    "ClaimSearchResults",
    "CommitHypothesisRequest",
    "DocumentChunk",
    "EvidenceFitAssessment",
    "EvidenceGapResolverRequest",
    "EvidenceGapResolverResult",
    "EmbeddingIndexResult",
    "EmbeddingMaintenanceResult",
    "FullTextTriageAgent",
    "FullTextTriageRequest",
    "FullTextTriageResult",
    "FullTextOpsAction",
    "FullTextOpsAgent",
    "FullTextOpsRequest",
    "FullTextOpsResult",
    "HypothesisPromotionCandidate",
    "HypothesisPromotionReportRequest",
    "HypothesisPromotionReportResult",
    "HypothesisDraft",
    "HypothesisProposalRequest",
    "HSAResearchService",
    "IngestionResult",
    "ClaimCuratorAgent",
    "CrossrefHarvesterV2",
    "EuropePMCHarvesterV2",
    "LocalRuleClaimExtractor",
    "LocalIngestionPipeline",
    "LocalDeterministicEmbeddingProvider",
    "OpenRouterEmbeddingProvider",
    "OpenAlexHarvesterV2",
    "PubMedHarvesterV2",
    "PostgresResearchRepository",
    "ResearchBriefEvaluationRecord",
    "ResearchBriefEvaluationRequest",
    "ResearchBriefEvaluationResult",
    "ResearchFollowupLeadResult",
    "ResearchFollowupLoopRequest",
    "ResearchFollowupLoopResult",
    "ResearchFollowupRefinementRequest",
    "ResearchFollowupRefinementResult",
    "ResearchFollowupResolverRequest",
    "ResearchFollowupResolverResult",
    "ResearchSource",
    "RetrievalSmokeRequest",
    "RetrievalSmokeResult",
    "SearchClaimsRequest",
    "SQLiteResearchRepository",
    "SourceQuery",
    "SourceRecommendation",
    "SourceScoutAgent",
    "SourceScoutRequest",
    "SourceScoutResult",
    "TherapyCommitteeReport",
    "TherapyCommitteeRequest",
    "TherapyCommitteeResult",
    "TherapyIdea",
    "TherapyIdeaLibraryRequest",
    "TherapyIdeaLibraryResult",
    "TherapyIdeaRecord",
    "ValidationAssayContext",
    "ValidationAgentResult",
    "ValidationGapSourceIngestRequest",
    "ValidationGapSourceIngestResult",
    "ValidationGapSourcePackRequest",
    "ValidationGapSourcePackResult",
    "ValidationGapSourceQuery",
    "ValidationPacket",
    "ValidationPacketRequest",
    "ValidationPacketResult",
    "ValidationRequest",
    "ValidationRequestQueueItem",
    "ValidationRequestQueueRequest",
    "ValidationRequestQueueResult",
    "ValidationToolCapability",
    "ValidationToolCatalogRequest",
    "ValidationToolCatalogResult",
    "ValidationToolMatchRequest",
    "ValidationToolMatchResult",
    "TherapyCommitteeValidationQueueRequest",
    "TherapyCommitteeValidationQueueResult",
    "XLinkedArticleFollowupRequest",
    "XLinkedArticleFollowupResult",
    "XTopicLinkedSource",
    "XTopicReviewAction",
    "XTopicReviewAgent",
    "XTopicReviewRequest",
    "XTopicReviewResult",
    "build_scholarly_source_queries",
    "build_chunk_embedding_text",
    "build_embedding_provider",
    "build_research_repository",
    "build_sql_repository",
    "build_validation_tool_catalog_report",
    "comparative_required_query",
    "curate_claims_for_repository",
    "extract_claims_for_repository",
    "get_harvester",
    "get_service",
    "index_embeddings_for_repository",
    "maintain_embedding_index",
    "match_validation_tools",
    "resolve_research_followup_leads",
    "scout_sources_for_repository",
    "triage_full_text_issue",
    "run_therapy_committee",
    "run_x_linked_article_followup",
]
