"""Watchlist lead collection for credible items not yet ready for ingestion."""

from __future__ import annotations

from collections.abc import Mapping, Sequence
import re
from typing import Any
from urllib.parse import urlparse
from uuid import UUID

from .contracts import (
    AgentRunRecord,
    ResearchLeadCollectRequest,
    ResearchLeadCollectResult,
    ResearchLeadRecord,
    XLinkedArticleReviewAction,
    XLinkedArticleReviewResult,
    XTopicReviewAction,
    XTopicReviewResult,
)
from .repository import ResearchRepository


X_LINKED_ARTICLE_REVIEW_AGENT_NAME = "x_linked_article_review_agent"
X_TOPIC_REVIEW_AGENT_NAME = "x_topic_review_agent"
WATCHLIST_AGENT_NAMES = (X_LINKED_ARTICLE_REVIEW_AGENT_NAME, X_TOPIC_REVIEW_AGENT_NAME)
WATCHLIST_STATUSES = ("new", "watching")
_URL_PATTERN = re.compile(r"https?://[^\s)>\"]+", re.I)
_TOPIC_TAG_PATTERNS = {
    "hemangiosarcoma": re.compile(r"\bhemangiosarcoma\b|\bhsa\b", re.I),
    "angiosarcoma": re.compile(r"\bangiosarcoma\b", re.I),
    "comparative_oncology": re.compile(r"\bcomparative oncology\b|\bcanine\b|\bdog\b|\bhuman\b", re.I),
    "therapy": re.compile(r"\btherapy\b|\btreatment\b|\bdrug\b|\binhibitor\b|\btrial\b", re.I),
    "biomarker": re.compile(r"\bbiomarker\b|\bexpression\b|\bprotein\b|\btarget\b", re.I),
}


def persist_research_leads_from_agent_result(
    repository: ResearchRepository,
    result: XLinkedArticleReviewResult | XTopicReviewResult,
) -> list[ResearchLeadRecord]:
    """Persist watchlist leads generated by a just-completed review agent result."""

    leads = _leads_from_result(result)
    return [repository.upsert_research_lead(lead) for lead in leads]


def collect_research_leads_from_agent_runs(
    repository: ResearchRepository,
    request: ResearchLeadCollectRequest,
) -> ResearchLeadCollectResult:
    """Scan recent persisted agent runs and collect watchlist leads idempotently."""

    result = ResearchLeadCollectResult()
    seen_run_ids: set[UUID] = set()
    existing_identity_keys = {
        lead.identity_key
        for lead in repository.list_research_leads(limit=None)
        if lead.identity_key
    }

    for agent_name in request.agent_names:
        for status in request.statuses:
            try:
                runs = repository.list_agent_runs(agent_name=agent_name, status=status, limit=request.limit)
            except Exception as exc:
                result.errors.append(f"{agent_name}:{status}: {exc}")
                continue
            for run in runs:
                if run.agent_run_id in seen_run_ids:
                    continue
                seen_run_ids.add(run.agent_run_id)
                result.agent_runs_seen += 1
                for lead in _leads_from_agent_run(run):
                    if lead.identity_key in existing_identity_keys and not request.include_existing:
                        result.skipped_existing += 1
                        continue
                    persisted = repository.upsert_research_lead(lead)
                    existing_identity_keys.add(persisted.identity_key)
                    result.items.append(persisted)
                    result.leads_created += 1
    return result


def active_research_leads_for_brief(
    repository: ResearchRepository,
    *,
    topic: str,
    disease_scope: str,
    source_key: str | None = None,
    limit: int = 20,
) -> list[ResearchLeadRecord]:
    """Return active leads as watchlist context for research-brief agents."""

    focus_terms = _focus_terms(f"{topic} {disease_scope}")
    candidates = repository.list_research_leads(
        statuses=list(WATCHLIST_STATUSES),
        source_key=source_key,
        limit=max(limit * 3, limit),
    )
    if focus_terms:
        candidates = [lead for lead in candidates if _lead_matches_focus(lead, focus_terms)]
    candidates.sort(key=lambda lead: (lead.priority, lead.created_at))
    return candidates[:limit]


def _leads_from_result(
    result: XLinkedArticleReviewResult | XTopicReviewResult,
) -> list[ResearchLeadRecord]:
    if isinstance(result, XLinkedArticleReviewResult):
        return [
            lead
            for action in result.actions
            if (lead := _lead_from_x_linked_article_action(action, result.agent_run_id)) is not None
        ]
    if isinstance(result, XTopicReviewResult):
        return [
            lead
            for action in result.actions
            if (lead := _lead_from_x_topic_action(action, result.agent_run_id)) is not None
        ]
    return []


def _leads_from_agent_run(run: AgentRunRecord) -> list[ResearchLeadRecord]:
    actions = run.output_payload.get("actions", [])
    if not isinstance(actions, list):
        return []
    leads: list[ResearchLeadRecord] = []
    for raw_action in actions:
        if not isinstance(raw_action, Mapping):
            continue
        if run.agent_name == X_LINKED_ARTICLE_REVIEW_AGENT_NAME:
            lead = _lead_from_x_linked_article_payload(raw_action, run.agent_run_id)
        elif run.agent_name == X_TOPIC_REVIEW_AGENT_NAME:
            lead = _lead_from_x_topic_payload(raw_action, run.agent_run_id)
        else:
            lead = None
        if lead is not None:
            leads.append(lead)
    return leads


def _lead_from_x_linked_article_action(
    action: XLinkedArticleReviewAction,
    agent_run_id: UUID | None,
) -> ResearchLeadRecord | None:
    if action.action != "needs_human_review":
        return None
    return _lead_from_x_linked_article_payload(action.model_dump(mode="json"), agent_run_id)


def _lead_from_x_linked_article_payload(
    action: Mapping[str, Any],
    agent_run_id: UUID | None,
) -> ResearchLeadRecord | None:
    if action.get("action") != "needs_human_review":
        return None
    metadata = _mapping(action.get("metadata"))
    title = _optional_str(metadata.get("title")) or f"Linked article review {action.get('source_record_id')}"
    url = _first_url([metadata.get("canonical_url"), *_list(action.get("evidence_refs"))])
    reason = _optional_str(action.get("reason"))
    text_for_tags = " ".join(
        [
            title or "",
            reason or "",
            " ".join(str(value) for value in _list(metadata.get("evidence_spans"))),
        ]
    )
    return ResearchLeadRecord(
        title=title,
        url=url,
        lead_type=_lead_type_from_url(url, default="linked_article"),
        status="new",
        priority=_priority_from_severity(_optional_str(action.get("severity"))),
        source_key="x_linked_article",
        origin_source_key="x_linked_article",
        origin_record_id=_optional_str(action.get("source_record_id")),
        origin_review_id=_optional_uuid(action.get("review_id")),
        origin_agent_run_id=agent_run_id,
        reason=reason,
        summary="Parsed linked article needs human review before it can become durable evidence.",
        evidence_refs=[str(value) for value in _list(action.get("evidence_refs")) if str(value).strip()],
        topic_tags=_topic_tags(text_for_tags),
        suggested_sources=_suggested_sources_from_links(_list(metadata.get("context_links"))),
        metadata={
            "agent_name": X_LINKED_ARTICLE_REVIEW_AGENT_NAME,
            "source_action": action.get("action"),
            "parser_confidence": metadata.get("parser_confidence"),
            "context_links": _list(metadata.get("context_links"))[:10],
            "context_link_count": metadata.get("context_link_count"),
        },
    )


def _lead_from_x_topic_action(
    action: XTopicReviewAction,
    agent_run_id: UUID | None,
) -> ResearchLeadRecord | None:
    if action.action != "needs_human_review":
        return None
    return _lead_from_x_topic_payload(action.model_dump(mode="json"), agent_run_id)


def _lead_from_x_topic_payload(
    action: Mapping[str, Any],
    agent_run_id: UUID | None,
) -> ResearchLeadRecord | None:
    if action.get("action") != "needs_human_review":
        return None
    metadata = _mapping(action.get("metadata"))
    source_record_id = _optional_str(action.get("source_record_id"))
    title = (
        _optional_str(metadata.get("title"))
        or _optional_str(metadata.get("text_preview"))
        or f"X topic candidate {source_record_id or 'unknown'} needs review"
    )
    url = _first_url(_list(action.get("evidence_refs")))
    reason = _optional_str(action.get("reason"))
    query_name = _optional_str(action.get("query_name"))
    text_for_tags = " ".join([title or "", reason or "", query_name or ""])
    return ResearchLeadRecord(
        title=title[:500] if title else None,
        url=url,
        lead_type=_lead_type_from_url(url, default="social_post"),
        status="new",
        priority=_priority_from_severity(_optional_str(action.get("severity"))),
        source_key="x_topic_monitor",
        origin_source_key="x_topic_monitor",
        origin_record_id=source_record_id,
        origin_agent_run_id=agent_run_id,
        reason=reason,
        summary="Social-monitoring candidate needs human review before source ingestion.",
        evidence_refs=[str(value) for value in _list(action.get("evidence_refs")) if str(value).strip()],
        topic_tags=_topic_tags(text_for_tags),
        suggested_sources=_suggested_sources_from_links(_list(action.get("evidence_refs"))),
        metadata={
            "agent_name": X_TOPIC_REVIEW_AGENT_NAME,
            "source_action": action.get("action"),
            "query_name": query_name,
            "username": _optional_str(action.get("username")),
        },
    )


def _priority_from_severity(severity: str | None) -> int:
    if severity == "blocking":
        return 40
    if severity == "watch":
        return 100
    return 180


def _lead_type_from_url(url: str | None, *, default: str) -> str:
    if not url:
        return default
    parsed = urlparse(url)
    haystack = f"{parsed.netloc} {parsed.path}".lower()
    if "abstract" in haystack or "conference" in haystack or "meeting" in haystack:
        return "conference_abstract"
    if "biorxiv" in haystack or "medrxiv" in haystack or "preprints" in haystack:
        return "preprint"
    if "press" in haystack or "news" in haystack:
        return "press_release"
    if parsed.netloc.endswith(".edu") or ".edu." in parsed.netloc:
        return "institutional_article"
    return default


def _topic_tags(text: str) -> list[str]:
    return [tag for tag, pattern in _TOPIC_TAG_PATTERNS.items() if pattern.search(text)]


def _suggested_sources_from_links(values: Sequence[Any]) -> list[str]:
    suggestions: list[str] = []
    for value in values:
        url = str(value)
        lowered = url.lower()
        if "pubmed" in lowered or "ncbi.nlm.nih.gov/pubmed" in lowered:
            suggestions.append("pubmed")
        if "pmc" in lowered or "ncbi.nlm.nih.gov/pmc" in lowered:
            suggestions.append("pmc_oa")
        if "doi.org" in lowered or "/doi/" in lowered:
            suggestions.append("crossref")
            suggestions.append("unpaywall")
        if "clinicaltrials.gov" in lowered:
            suggestions.append("clinicaltrials_gov")
    return _dedupe_strings(suggestions)


def _focus_terms(value: str) -> set[str]:
    stopwords = {"and", "with", "from", "human", "canine", "therapy", "research", "evidence"}
    return {
        term
        for term in re.findall(r"[a-z0-9]{4,}", value.lower())
        if term not in stopwords
    }


def _lead_matches_focus(lead: ResearchLeadRecord, focus_terms: set[str]) -> bool:
    haystack = " ".join(
        [
            lead.title or "",
            lead.reason or "",
            lead.summary or "",
            " ".join(lead.topic_tags),
            " ".join(lead.evidence_refs),
        ]
    ).lower()
    return any(term in haystack for term in focus_terms)


def _first_url(values: Sequence[Any]) -> str | None:
    for value in values:
        text = str(value)
        match = _URL_PATTERN.search(text)
        if match:
            return match.group(0).split("#", 1)[0].rstrip(").,;")
    return None


def _optional_uuid(value: Any) -> UUID | None:
    if value is None:
        return None
    if isinstance(value, UUID):
        return value
    try:
        return UUID(str(value))
    except ValueError:
        return None


def _optional_str(value: Any) -> str | None:
    if value is None:
        return None
    text = str(value).strip()
    return text or None


def _list(value: Any) -> list[Any]:
    return value if isinstance(value, list) else []


def _mapping(value: Any) -> Mapping[str, Any]:
    return value if isinstance(value, Mapping) else {}


def _dedupe_strings(values: Sequence[str]) -> list[str]:
    deduped: list[str] = []
    seen: set[str] = set()
    for value in values:
        normalized = value.strip()
        if not normalized or normalized in seen:
            continue
        deduped.append(normalized)
        seen.add(normalized)
    return deduped
