"""Initial source registry for Ingestion Bridge v2."""

from __future__ import annotations

from .contracts import ResearchSource, SourceKind


INITIAL_SOURCES: tuple[ResearchSource, ...] = (
    ResearchSource(
        source_key="pubmed",
        display_name="PubMed",
        source_kind=SourceKind.SCHOLARLY_METADATA,
        base_url="https://pubmed.ncbi.nlm.nih.gov/",
        documentation_url="https://www.ncbi.nlm.nih.gov/books/NBK25501/",
        license_policy="metadata_and_abstracts",
        requires_api_key=False,
        priority=10,
        phase=1,
        capabilities=["metadata_search", "pmid_resolution", "abstracts", "mesh_terms"],
        notes="Keep as a core biomedical search source but do not treat it as complete coverage.",
    ),
    ResearchSource(
        source_key="europe_pmc",
        display_name="Europe PMC",
        source_kind=SourceKind.SCHOLARLY_METADATA,
        base_url="https://europepmc.org/",
        documentation_url="https://europepmc.org/RestfulWebService",
        license_policy="metadata_plus_open_access_when_licensed",
        requires_api_key=False,
        priority=20,
        phase=1,
        capabilities=["metadata_search", "open_access_links", "annotations", "citations", "full_text_links"],
    ),
    ResearchSource(
        source_key="openalex",
        display_name="OpenAlex",
        source_kind=SourceKind.SCHOLARLY_METADATA,
        base_url="https://openalex.org/",
        documentation_url="https://developers.openalex.org/",
        license_policy="metadata",
        requires_api_key=False,
        priority=30,
        phase=1,
        capabilities=["metadata_search", "source_registry", "citation_graph", "author_institution_graph"],
    ),
    ResearchSource(
        source_key="crossref",
        display_name="Crossref",
        source_kind=SourceKind.SCHOLARLY_METADATA,
        base_url="https://www.crossref.org/",
        documentation_url="https://www.production.crossref.org/documentation/retrieve-metadata/rest-api/",
        license_policy="metadata",
        requires_api_key=False,
        priority=40,
        phase=1,
        capabilities=["doi_resolution", "journal_issn_queries", "license_links", "funder_metadata"],
    ),
    ResearchSource(
        source_key="pmc_oa",
        display_name="PMC Open Access",
        source_kind=SourceKind.OPEN_ACCESS_FULL_TEXT,
        base_url="https://pmc.ncbi.nlm.nih.gov/",
        documentation_url="https://pmc.ncbi.nlm.nih.gov/tools/oai/",
        license_policy="store_only_when_license_allows",
        requires_api_key=False,
        priority=50,
        phase=1,
        capabilities=["legal_full_text", "jats_xml", "oai_pmh", "license_metadata"],
    ),
    ResearchSource(
        source_key="unpaywall",
        display_name="Unpaywall",
        source_kind=SourceKind.SCHOLARLY_METADATA,
        base_url="https://unpaywall.org/",
        documentation_url="https://support.unpaywall.org/support/solutions/articles/44001977396-how-do-i-use-the-title-search-api-",
        license_policy="metadata_and_open_access_location_links",
        requires_api_key=False,
        priority=55,
        phase=1,
        capabilities=["oa_discovery", "doi_resolution", "license_metadata", "full_text_location_links"],
        notes=(
            "Use DOI metadata for open-access discovery; keep title-search manual until the public endpoint is stable. "
            "Do not treat linked PDFs as storable full text until a license-aware fetch lane validates them."
        ),
    ),
    ResearchSource(
        source_key="current_papers",
        display_name="Existing papers table",
        source_kind=SourceKind.INTERNAL,
        license_policy="internal_backfill",
        requires_api_key=False,
        priority=60,
        phase=1,
        capabilities=["backfill", "legacy_paper_records"],
    ),
    ResearchSource(
        source_key="current_knowledge_entries",
        display_name="Existing corpus knowledge entries",
        source_kind=SourceKind.INTERNAL,
        license_policy="internal_backfill",
        requires_api_key=False,
        priority=70,
        phase=1,
        capabilities=["backfill", "legacy_knowledge_records"],
    ),
    ResearchSource(
        source_key="x_topic_monitor",
        display_name="X Topic Monitor",
        source_kind=SourceKind.INTERNAL,
        base_url="https://x.com/",
        documentation_url="https://docs.twitterapi.io/api-reference/endpoint/tweet_advanced_search",
        license_policy="third_party_api_review_queue",
        requires_api_key=True,
        enabled=False,
        priority=95,
        phase=1,
        capabilities=["topic_monitoring", "manual_review_queue", "twitterapi_io_advanced_search"],
        notes=(
            "Manual review-only social monitoring. Posts are discovery signals, not scientific evidence; "
            "durable linked sources should be harvested through primary APIs."
        ),
    ),
    ResearchSource(
        source_key="clinicaltrials_gov",
        display_name="ClinicalTrials.gov",
        source_kind=SourceKind.CLINICAL_TRIAL,
        base_url="https://clinicaltrials.gov/",
        documentation_url="https://clinicaltrials.gov/data-about-studies/learn-about-api",
        license_policy="metadata",
        requires_api_key=False,
        priority=110,
        phase=2,
        capabilities=["trial_search", "interventions", "conditions", "status", "results"],
    ),
    ResearchSource(
        source_key="avma_vctr",
        display_name="AVMA Veterinary Clinical Trials Registry",
        source_kind=SourceKind.VETERINARY_TRIAL,
        base_url="https://veterinaryclinicaltrials.org/",
        documentation_url="https://veterinaryclinicaltrials.org/avma/studies/search/json/",
        license_policy="link_and_registry_metadata",
        requires_api_key=False,
        priority=120,
        phase=2,
        capabilities=[
            "public_json_search",
            "veterinary_trials",
            "canine_trials",
            "recruiting_status",
            "study_cards",
            "detail_snapshots_optional",
        ],
        notes=(
            "Public Studypages JSON search endpoint discovered during live testing. "
            "Use API-backed link/metadata ingest first; keep page snapshots approval-gated for richer details."
        ),
    ),
    ResearchSource(
        source_key="icdc",
        display_name="NCI Integrated Canine Data Commons",
        source_kind=SourceKind.CANINE_ONCOLOGY,
        base_url="https://caninecommons.cancer.gov/",
        license_policy="dataset_metadata_and_authorized_access",
        requires_api_key=False,
        priority=130,
        phase=2,
        capabilities=["canine_clinical_data", "genomics", "comparative_oncology", "dataset_links"],
    ),
    ResearchSource(
        source_key="geo",
        display_name="NCBI Gene Expression Omnibus",
        source_kind=SourceKind.OMICS,
        base_url="https://www.ncbi.nlm.nih.gov/geo/",
        documentation_url="https://www.ncbi.nlm.nih.gov/geo/info/geo_paccess.html",
        license_policy="metadata_and_dataset_links",
        requires_api_key=False,
        priority=135,
        phase=2,
        capabilities=["dataset_metadata", "sample_metadata", "geo_accessions", "ftp_links", "bioproject_links"],
        notes="Use E-utilities for metadata first; raw matrix/download handling should be artifact-managed later.",
    ),
    ResearchSource(
        source_key="sra",
        display_name="NCBI Sequence Read Archive",
        source_kind=SourceKind.OMICS,
        base_url="https://www.ncbi.nlm.nih.gov/sra/",
        documentation_url="https://www.ncbi.nlm.nih.gov/books/NBK25497/",
        license_policy="metadata_and_dataset_links",
        requires_api_key=False,
        priority=140,
        phase=2,
        capabilities=["run_metadata", "experiment_metadata", "bioproject_links", "biosample_links", "sequence_file_links"],
        notes="Ingest run and experiment metadata first; raw sequence download should remain approval gated.",
    ),
    ResearchSource(
        source_key="pubchem",
        display_name="PubChem",
        source_kind=SourceKind.CHEMISTRY,
        base_url="https://pubchem.ncbi.nlm.nih.gov/",
        documentation_url="https://pubchem.ncbi.nlm.nih.gov/docs/pug-rest",
        license_policy="metadata",
        requires_api_key=False,
        priority=210,
        phase=3,
        capabilities=["compound_resolution", "synonyms", "properties", "bioassays"],
    ),
    ResearchSource(
        source_key="chembl",
        display_name="ChEMBL",
        source_kind=SourceKind.CHEMISTRY,
        base_url="https://www.ebi.ac.uk/chembl/",
        documentation_url="https://chembl.gitbook.io/chembl-interface-documentation/web-services",
        license_policy="cc_by_sa",
        requires_api_key=False,
        priority=220,
        phase=3,
        capabilities=["bioactivity", "compound_resolution", "targets", "assays"],
    ),
    ResearchSource(
        source_key="uniprot",
        display_name="UniProt",
        source_kind=SourceKind.TARGET_STRUCTURE,
        base_url="https://www.uniprot.org/",
        documentation_url="https://www.uniprot.org/api-documentation",
        license_policy="metadata",
        requires_api_key=False,
        priority=230,
        phase=3,
        capabilities=["protein_resolution", "orthologs", "sequence", "annotations"],
    ),
    ResearchSource(
        source_key="rcsb_pdb",
        display_name="RCSB PDB",
        source_kind=SourceKind.TARGET_STRUCTURE,
        base_url="https://www.rcsb.org/",
        documentation_url="https://data.rcsb.org/index.html",
        license_policy="metadata_and_structure_links",
        requires_api_key=False,
        priority=240,
        phase=3,
        capabilities=["structure_metadata", "pdb_resolution", "ligands", "experimental_details"],
    ),
    ResearchSource(
        source_key="openfda_animal_events",
        display_name="openFDA Animal and Veterinary Adverse Events",
        source_kind=SourceKind.SAFETY,
        base_url="https://open.fda.gov/apis/animalandveterinary/event/",
        documentation_url="https://open.fda.gov/apis/animalandveterinary/event/",
        license_policy="public_safety_reports_with_limitations",
        requires_api_key=False,
        priority=250,
        phase=3,
        capabilities=["animal_adverse_events", "safety_signals", "quarterly_updates"],
    ),
)


def get_initial_sources() -> list[ResearchSource]:
    """Return a mutable copy of the source registry."""

    return [source.model_copy(deep=True) for source in INITIAL_SOURCES]


def get_source(source_key: str) -> ResearchSource | None:
    """Look up a source by stable source key."""

    for source in INITIAL_SOURCES:
        if source.source_key == source_key:
            return source.model_copy(deep=True)
    return None
